### ISSUE TITLE
Error al registrar customer en produccion

### ISSUE THREAD

**Issue by alacret** [cobuildlab/massone-web#207]
El cliente reporta este error.

Por favor, ten en cuenta que estas son las ramas de produccion, para solucionar y probar esto tienes que hacer una rama `fix/<issue name>` a partir de la rama `prod` de cada repo

![2019-04-29](https://user-images.githubusercontent.com/918895/56912620-a26cb400-6a7d-11e9-9b1d-3cf685c4ff83.png)

**Comment by pamelagbl** [comment]
@overflow ese error sucede en web pero cuando dejo el campo en blanco...

**Comment by pamelagbl** [comment]
@overflow @alacret es porque tiene un numero. Esos campos no permiten numeros
